language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
services:
  - postgresql
script:
  - cd src
  - pytest -s
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
