version: '3'
services:
    database:
      container_name: postgres
      image: postgres:latest
      env_file: config.env
      ports:
        - "5432:5432"
      volumes:
        - ./data:/var/lib/postgresql/data

    src:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        env_file: config.env
        volumes:
            - ./src:/src
        depends_on:
            - database
        links:
            - database:database
volumes:
  db_volume: